### ISSUE TITLE
Do templates implicitly set properties on its controller?

### ISSUE THREAD

**Issue by lljr** [rockandrollwithemberjs/rarwe-issues#472] opened 2020-07-25 19:05 UTC
```handlebars
{{!-- app/templates/bands/new.hbs --}}

<input
 id="name"
 class="w-full text-gray-800 bg-white border rounded-md py-2 px-4"
value={{this.name}}
 {{on "input" (set this.name (get _ "target.value"))}}
 />
```

It's context only has 
```javascript
import Controller from '@ember/controller';
import { action } from '@ember/object';
import { dasherize } from '@ember/string';
import { Band } from 'rarwe/routes/bands';

export default class BandsNewController extends Controller {
  @action
  saveBand() {
    new Band({ name: this.name, slug: dasherize(this.name)})
  }
}
```

Shouldn't the property be declared and tracked in its controller like `@tracked name = ''`

The js route file also uses the `name` property 

```javascript
import Route from '@ember/routing/route';

export default class BandsNewRoute extends Route {
  resetController(controller) {
    controller.name = '';
  }

}
```
How does that work? How does the route know of `this.name` if its not declared in the controller?

**Comment by balinterdi** [comment] 2020-07-30 15:33
I think that's a duplicate of #471, so closing.

**Closed by balinterdi** 2020-07-30 15:33 UTC
