### ISSUE TITLE
The `content` option in your Tailwind CSS configuration is missing or empty.

### ISSUE THREAD

**Issue by JSAtwal25** [rockandrollwithemberjs/rarwe-issues#537] opened 2022-04-13 23:05 UTC
I received this warning when trying to implement tailwind into the project. I was able to get it working by adding a 'tailwind.config.js' file in the root directory according to [this page](https://tailwindcss.com/docs/content-configuration) as well as adding an 'options' key in the tailwindcss plugins object. That options key has an object as its value with a 'config' key paired with a value that is a string pointing to my 'tailwind.config.js' file.

**Comment by balinterdi** [comment] 2022-04-21 16:48
@JSAtwal25 Did you get this warning when *adding* tailwindcss as a dependency and then re-starting the server?

Could you confirm you're using Tailwind@2 as in the app? I don't think I've seen this warning before but I might be wrong.

Thank you.

**Comment by JSAtwal25** [comment] 2022-04-21 18:06
Hey @balinterdi, I was able to add tailwindcss as a dependency without any issues. The warning came when starting the server and did not allow any of the styling to apply to the application.

I am using Tailwind@3.0.24, I don't believe a version number was specified in the book but I could be wrong.

Warning Image: 
<img width="1043" alt="Screen Shot 2022-04-13 at 4 22 41 PM" src="https://user-images.githubusercontent.com/69940833/164523138-8896fc31-19ff-458a-9e31-82b1856ee058.png">

**Comment by balinterdi** [comment] 2022-04-22 08:48
I think you're reading an older version of the book as I've modified the npm install to specifically install Tailwind@2  two updates before, in 4.1 (and I just realize this is a duplicate of #526).

Here is the relevant section:

<img width="991" alt="Screenshot 2022-04-22 at 10 44 41" src="https://user-images.githubusercontent.com/5022/164652577-74ed8596-e781-43af-9ddd-226f082f30ff.png">

**Closed** 2022-07-05 07:35 UTC
Labels: duplicate
